TRAIN:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["/scratch/at4091/stl10/data/unsupervised_train_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  MMAP_MODE: True
  DEFAULT_GRAY_IMG_SIZE: 96
  TRANSFORMS: [
    ["RandomGrayscale", {"args": [0.3]}],
    ["ssl_jigsaw", {"indices":[0], "args": ["/scratch/at4091/stl10/data/permutations_100.npy"]}],
  ]

TEST:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["/scratch/at4091/stl10/data/unsupervised_test_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 128
  MMAP_MODE: True
  DEFAULT_GRAY_IMG_SIZE: 96
  TRANSFORMS: [
    ["ssl_jigsaw", {"indices":[0], "args": ["/scratch/at4091/stl10/data/unsupervised_train_images.npy"]}],
  ]


MODEL:
  TRUNK:
    TYPE: "alexnet_jigsaw_bn"
  HEAD:
    PARAMS: [["mlp", {"dims": [4608, 4096, 100]}]]
    APPLY_BATCHNORM: True
  FEATURE_EVAL_MODE: False
  EVAL_FEATURES: []

# Training Parameters
TRAINER:
  TRAIN_LOOP: "generic_train_loop"
  TRAIN_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  EVAL_LOOP: "generic_eval_loop"
  EVAL_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  MAX_EPOCHS: 30
  NUM_WORKERS: 20

OPTIMIZER:
  TYPE: "adam"
  BASE_LR: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  DAMPENING: 0
  NESTEROV: True

SCHEDULER:
  TYPE: "step"
  STEP_SIZE: 25
  GAMMA: 0.1

CHECKPOINT:
  DIR: "./checkpoint_unsupervised_training"

VERBOSE: True
