TRAIN:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["data/unsupervised_train_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  TRANSFORMS: [
    ["RandomHorizontalFlip"],
    ["RandomRotation", {"args": [10]}],
    ["RandomResizedCrop", {"args": [75, [0.6, 1.0]]}],
    ["ssl_rotate", {"indices": [0]}],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]

TEST:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["data/unsupervised_test_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  TRANSFORMS: [
    ["Resize", {"args": [75]}],
    ["ssl_rotate"],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]

MODEL:
  TRUNK:
    TYPE: "revnet50"
    KWARGS: {'k': 2}
  HEAD:
    PARAMS: [["mlp", {"dims": [2048, 4]}]]
    APPLY_BATCHNORM: True
  FEATURE_EVAL_MODE: False
  EVAL_FEATURES: []

# Training Parameters
TRAINER:
  TRAIN_LOOP: "generic_train_loop"
  TRAIN_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  EVAL_LOOP: "generic_eval_loop"
  EVAL_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  MAX_EPOCHS: 300

OPTIMIZER:
  TYPE: "adam"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0

SCHEDULER:
  # TYPE: "step"
  # KWARGS: {'step_size': 30, 'gamma': 0.1}
  TYPE: "plateau"
  KWARGS: {"patience": 10, "verbose": True, "threshold": .01}
  STEP_METERS: ["loss"]

CHECKPOINT:
  DIR: "./checkpoint/final_revnev_2"

VISDOM:
  ENV: "final_revnet_2"
  CONFIG: {"server": "log-0"}

VERBOSE: True
