TRAIN:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["data/unsupervised_train_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  TRANSFORMS: [
    ["ssl_rotate", {"indices":[0]}],
    ["RandomHorizontalFlip"],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]

TEST:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["data/unsupervised_test_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  TRANSFORMS: [
    ["ssl_rotate"],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]


MODEL:
  TRUNK:
    TYPE: "resnet50"
  HEAD:
    PARAMS: [["mlp", {"dims": [2048, 4]}]]
    APPLY_BATCHNORM: True
  FEATURE_EVAL_MODE: False
  EVAL_FEATURES: []

# Training Parameters
TRAINER:
  TRAIN_LOOP: "generic_train_loop"
  TRAIN_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  EVAL_LOOP: "generic_eval_loop"
  EVAL_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  MAX_EPOCHS: 90

OPTIMIZER:
  TYPE: "adam"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0

SCHEDULER:
  TYPE: "step"
  KWARGS: {'step_size': 30, 'gamma': 0.1}

CHECKPOINT:
  DIR: "./checkpoint_pretext_resnet_rotation"

VERBOSE: True
