TRAIN:
  DATA_SOURCES: [disk]
  DATA_PATHS: [ "data/unsupervised_train_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 256
  DEFAULT_GRAY_IMG_SIZE: 96
  TRANSFORMS: [
    ["RandomCrop", {"args": [75]}],
    ["RandomRotation", {"args": [10]}],
    ["RandomHorizontalFlip"],
    ["ssl_rotate", {"indices": [0]}],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]

TEST:
  DATA_SOURCES: [disk]
  DATA_PATHS: ["data/unsupervised_test_images.npy"]
  LABEL_SOURCES: [disk]
  LABEL_PATHS: []
  BATCH_SIZE: 128
  DEFAULT_GRAY_IMG_SIZE: 96
  TRANSFORMS: [
    ["CenterCrop", {"args": [75]}],
    ["ssl_rotate", {"indices":[0]}],
    ["ToTensor"],
    ["Normalize", {"args": [[0.44671062, 0.43980984, 0.40664645], [0.26034098, 0.25657727, 0.27126738]]}],
  ]


MODEL:
  TRUNK:
    TYPE: "vgg_a"
  HEAD:
    PARAMS: [["eval_mlp", {"in_channels": 512, "dims": [2048, 4]}]]
    APPLY_BATCHNORM: True
  FEATURE_EVAL_MODE: False
  EVAL_FEATURES: []

# Training Parameters
TRAINER:
  TRAIN_LOOP: "generic_train_loop"
  TRAIN_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  EVAL_LOOP: "generic_eval_loop"
  EVAL_METERS: {"accuracy": {"topk": [1]}, "loss": {}}
  MAX_EPOCHS: 100
  NUM_WORKERS: 20

OPTIMIZER:
  TYPE: "sgd"
  BASE_LR: 0.1
  WEIGHT_DECAY: 0.0001
  KWARGS: {'momentum': 0.9, 'dampening': 0, 'nesterov': True}

SCHEDULER:
  TYPE: "step"
  KWARGS: {'step_size': 25, 'gamma': 0.1}

CHECKPOINT:
  DIR: "./checkpoint/pretext_vgg_aug"

VISDOM:
  ENV: "pretext_vgg"
  CONFIG: {"server": "log-0"}

VERBOSE: True
